POST http://localhost:3000/register/
Content-Type: application/json

{
    "username" : "Sameer",
    "password" : "123456"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username" : "Mayur",
    "password" : "123456"
}

###

GET http://localhost:3000/home/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heXVyIiwiaWF0IjoxNzU0MjA5NzIxLCJleHAiOjE3NTQyMTMzMjF9.merIka6nZFtz0aGkUw5bbmeaW-vAGCLmfH5Xa5UXlTA

###